# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ayushi/opencv

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ayushi/opencv

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ayushi/opencv/CMakeFiles /home/ayushi/opencv/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ayushi/opencv/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cfarAlgo

# Build rule for target.
cfarAlgo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cfarAlgo
.PHONY : cfarAlgo

# fast build rule for target.
cfarAlgo/fast:
	$(MAKE) -f CMakeFiles/cfarAlgo.dir/build.make CMakeFiles/cfarAlgo.dir/build
.PHONY : cfarAlgo/fast

#=============================================================================
# Target rules for targets named histogram

# Build rule for target.
histogram: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 histogram
.PHONY : histogram

# fast build rule for target.
histogram/fast:
	$(MAKE) -f CMakeFiles/histogram.dir/build.make CMakeFiles/histogram.dir/build
.PHONY : histogram/fast

#=============================================================================
# Target rules for targets named t_image

# Build rule for target.
t_image: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 t_image
.PHONY : t_image

# fast build rule for target.
t_image/fast:
	$(MAKE) -f CMakeFiles/t_image.dir/build.make CMakeFiles/t_image.dir/build
.PHONY : t_image/fast

#=============================================================================
# Target rules for targets named fort

# Build rule for target.
fort: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fort
.PHONY : fort

# fast build rule for target.
fort/fast:
	$(MAKE) -f CMakeFiles/fort.dir/build.make CMakeFiles/fort.dir/build
.PHONY : fort/fast

#=============================================================================
# Target rules for targets named cfar

# Build rule for target.
cfar: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cfar
.PHONY : cfar

# fast build rule for target.
cfar/fast:
	$(MAKE) -f CMakeFiles/cfar.dir/build.make CMakeFiles/cfar.dir/build
.PHONY : cfar/fast

#=============================================================================
# Target rules for targets named kalman_cfar

# Build rule for target.
kalman_cfar: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kalman_cfar
.PHONY : kalman_cfar

# fast build rule for target.
kalman_cfar/fast:
	$(MAKE) -f CMakeFiles/kalman_cfar.dir/build.make CMakeFiles/kalman_cfar.dir/build
.PHONY : kalman_cfar/fast

#=============================================================================
# Target rules for targets named foil

# Build rule for target.
foil: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 foil
.PHONY : foil

# fast build rule for target.
foil/fast:
	$(MAKE) -f CMakeFiles/foil.dir/build.make CMakeFiles/foil.dir/build
.PHONY : foil/fast

#=============================================================================
# Target rules for targets named t_contour

# Build rule for target.
t_contour: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 t_contour
.PHONY : t_contour

# fast build rule for target.
t_contour/fast:
	$(MAKE) -f CMakeFiles/t_contour.dir/build.make CMakeFiles/t_contour.dir/build
.PHONY : t_contour/fast

#=============================================================================
# Target rules for targets named KFtrack

# Build rule for target.
KFtrack: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 KFtrack
.PHONY : KFtrack

# fast build rule for target.
KFtrack/fast:
	$(MAKE) -f CMakeFiles/KFtrack.dir/build.make CMakeFiles/KFtrack.dir/build
.PHONY : KFtrack/fast

#=============================================================================
# Target rules for targets named t_speed

# Build rule for target.
t_speed: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 t_speed
.PHONY : t_speed

# fast build rule for target.
t_speed/fast:
	$(MAKE) -f CMakeFiles/t_speed.dir/build.make CMakeFiles/t_speed.dir/build
.PHONY : t_speed/fast

#=============================================================================
# Target rules for targets named blur

# Build rule for target.
blur: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 blur
.PHONY : blur

# fast build rule for target.
blur/fast:
	$(MAKE) -f CMakeFiles/blur.dir/build.make CMakeFiles/blur.dir/build
.PHONY : blur/fast

#=============================================================================
# Target rules for targets named col1

# Build rule for target.
col1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 col1
.PHONY : col1

# fast build rule for target.
col1/fast:
	$(MAKE) -f CMakeFiles/col1.dir/build.make CMakeFiles/col1.dir/build
.PHONY : col1/fast

#=============================================================================
# Target rules for targets named thresh

# Build rule for target.
thresh: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 thresh
.PHONY : thresh

# fast build rule for target.
thresh/fast:
	$(MAKE) -f CMakeFiles/thresh.dir/build.make CMakeFiles/thresh.dir/build
.PHONY : thresh/fast

#=============================================================================
# Target rules for targets named ycrcb

# Build rule for target.
ycrcb: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ycrcb
.PHONY : ycrcb

# fast build rule for target.
ycrcb/fast:
	$(MAKE) -f CMakeFiles/ycrcb.dir/build.make CMakeFiles/ycrcb.dir/build
.PHONY : ycrcb/fast

#=============================================================================
# Target rules for targets named segm

# Build rule for target.
segm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 segm
.PHONY : segm

# fast build rule for target.
segm/fast:
	$(MAKE) -f CMakeFiles/segm.dir/build.make CMakeFiles/segm.dir/build
.PHONY : segm/fast

src/CFARnKF.o: src/CFARnKF.cpp.o

.PHONY : src/CFARnKF.o

# target to build an object file
src/CFARnKF.cpp.o:
	$(MAKE) -f CMakeFiles/kalman_cfar.dir/build.make CMakeFiles/kalman_cfar.dir/src/CFARnKF.cpp.o
.PHONY : src/CFARnKF.cpp.o

src/CFARnKF.i: src/CFARnKF.cpp.i

.PHONY : src/CFARnKF.i

# target to preprocess a source file
src/CFARnKF.cpp.i:
	$(MAKE) -f CMakeFiles/kalman_cfar.dir/build.make CMakeFiles/kalman_cfar.dir/src/CFARnKF.cpp.i
.PHONY : src/CFARnKF.cpp.i

src/CFARnKF.s: src/CFARnKF.cpp.s

.PHONY : src/CFARnKF.s

# target to generate assembly for a file
src/CFARnKF.cpp.s:
	$(MAKE) -f CMakeFiles/kalman_cfar.dir/build.make CMakeFiles/kalman_cfar.dir/src/CFARnKF.cpp.s
.PHONY : src/CFARnKF.cpp.s

src/KFtrack.o: src/KFtrack.cpp.o

.PHONY : src/KFtrack.o

# target to build an object file
src/KFtrack.cpp.o:
	$(MAKE) -f CMakeFiles/KFtrack.dir/build.make CMakeFiles/KFtrack.dir/src/KFtrack.cpp.o
.PHONY : src/KFtrack.cpp.o

src/KFtrack.i: src/KFtrack.cpp.i

.PHONY : src/KFtrack.i

# target to preprocess a source file
src/KFtrack.cpp.i:
	$(MAKE) -f CMakeFiles/KFtrack.dir/build.make CMakeFiles/KFtrack.dir/src/KFtrack.cpp.i
.PHONY : src/KFtrack.cpp.i

src/KFtrack.s: src/KFtrack.cpp.s

.PHONY : src/KFtrack.s

# target to generate assembly for a file
src/KFtrack.cpp.s:
	$(MAKE) -f CMakeFiles/KFtrack.dir/build.make CMakeFiles/KFtrack.dir/src/KFtrack.cpp.s
.PHONY : src/KFtrack.cpp.s

src/Smoothing.o: src/Smoothing.cpp.o

.PHONY : src/Smoothing.o

# target to build an object file
src/Smoothing.cpp.o:
	$(MAKE) -f CMakeFiles/blur.dir/build.make CMakeFiles/blur.dir/src/Smoothing.cpp.o
.PHONY : src/Smoothing.cpp.o

src/Smoothing.i: src/Smoothing.cpp.i

.PHONY : src/Smoothing.i

# target to preprocess a source file
src/Smoothing.cpp.i:
	$(MAKE) -f CMakeFiles/blur.dir/build.make CMakeFiles/blur.dir/src/Smoothing.cpp.i
.PHONY : src/Smoothing.cpp.i

src/Smoothing.s: src/Smoothing.cpp.s

.PHONY : src/Smoothing.s

# target to generate assembly for a file
src/Smoothing.cpp.s:
	$(MAKE) -f CMakeFiles/blur.dir/build.make CMakeFiles/blur.dir/src/Smoothing.cpp.s
.PHONY : src/Smoothing.cpp.s

src/Ycrcb.o: src/Ycrcb.cpp.o

.PHONY : src/Ycrcb.o

# target to build an object file
src/Ycrcb.cpp.o:
	$(MAKE) -f CMakeFiles/ycrcb.dir/build.make CMakeFiles/ycrcb.dir/src/Ycrcb.cpp.o
.PHONY : src/Ycrcb.cpp.o

src/Ycrcb.i: src/Ycrcb.cpp.i

.PHONY : src/Ycrcb.i

# target to preprocess a source file
src/Ycrcb.cpp.i:
	$(MAKE) -f CMakeFiles/ycrcb.dir/build.make CMakeFiles/ycrcb.dir/src/Ycrcb.cpp.i
.PHONY : src/Ycrcb.cpp.i

src/Ycrcb.s: src/Ycrcb.cpp.s

.PHONY : src/Ycrcb.s

# target to generate assembly for a file
src/Ycrcb.cpp.s:
	$(MAKE) -f CMakeFiles/ycrcb.dir/build.make CMakeFiles/ycrcb.dir/src/Ycrcb.cpp.s
.PHONY : src/Ycrcb.cpp.s

src/airfoil.o: src/airfoil.cpp.o

.PHONY : src/airfoil.o

# target to build an object file
src/airfoil.cpp.o:
	$(MAKE) -f CMakeFiles/foil.dir/build.make CMakeFiles/foil.dir/src/airfoil.cpp.o
.PHONY : src/airfoil.cpp.o

src/airfoil.i: src/airfoil.cpp.i

.PHONY : src/airfoil.i

# target to preprocess a source file
src/airfoil.cpp.i:
	$(MAKE) -f CMakeFiles/foil.dir/build.make CMakeFiles/foil.dir/src/airfoil.cpp.i
.PHONY : src/airfoil.cpp.i

src/airfoil.s: src/airfoil.cpp.s

.PHONY : src/airfoil.s

# target to generate assembly for a file
src/airfoil.cpp.s:
	$(MAKE) -f CMakeFiles/foil.dir/build.make CMakeFiles/foil.dir/src/airfoil.cpp.s
.PHONY : src/airfoil.cpp.s

src/cfar.o: src/cfar.cpp.o

.PHONY : src/cfar.o

# target to build an object file
src/cfar.cpp.o:
	$(MAKE) -f CMakeFiles/cfar.dir/build.make CMakeFiles/cfar.dir/src/cfar.cpp.o
.PHONY : src/cfar.cpp.o

src/cfar.i: src/cfar.cpp.i

.PHONY : src/cfar.i

# target to preprocess a source file
src/cfar.cpp.i:
	$(MAKE) -f CMakeFiles/cfar.dir/build.make CMakeFiles/cfar.dir/src/cfar.cpp.i
.PHONY : src/cfar.cpp.i

src/cfar.s: src/cfar.cpp.s

.PHONY : src/cfar.s

# target to generate assembly for a file
src/cfar.cpp.s:
	$(MAKE) -f CMakeFiles/cfar.dir/build.make CMakeFiles/cfar.dir/src/cfar.cpp.s
.PHONY : src/cfar.cpp.s

src/cfarAlgo.o: src/cfarAlgo.cpp.o

.PHONY : src/cfarAlgo.o

# target to build an object file
src/cfarAlgo.cpp.o:
	$(MAKE) -f CMakeFiles/cfarAlgo.dir/build.make CMakeFiles/cfarAlgo.dir/src/cfarAlgo.cpp.o
.PHONY : src/cfarAlgo.cpp.o

src/cfarAlgo.i: src/cfarAlgo.cpp.i

.PHONY : src/cfarAlgo.i

# target to preprocess a source file
src/cfarAlgo.cpp.i:
	$(MAKE) -f CMakeFiles/cfarAlgo.dir/build.make CMakeFiles/cfarAlgo.dir/src/cfarAlgo.cpp.i
.PHONY : src/cfarAlgo.cpp.i

src/cfarAlgo.s: src/cfarAlgo.cpp.s

.PHONY : src/cfarAlgo.s

# target to generate assembly for a file
src/cfarAlgo.cpp.s:
	$(MAKE) -f CMakeFiles/cfarAlgo.dir/build.make CMakeFiles/cfarAlgo.dir/src/cfarAlgo.cpp.s
.PHONY : src/cfarAlgo.cpp.s

src/colonizer1.o: src/colonizer1.cpp.o

.PHONY : src/colonizer1.o

# target to build an object file
src/colonizer1.cpp.o:
	$(MAKE) -f CMakeFiles/col1.dir/build.make CMakeFiles/col1.dir/src/colonizer1.cpp.o
.PHONY : src/colonizer1.cpp.o

src/colonizer1.i: src/colonizer1.cpp.i

.PHONY : src/colonizer1.i

# target to preprocess a source file
src/colonizer1.cpp.i:
	$(MAKE) -f CMakeFiles/col1.dir/build.make CMakeFiles/col1.dir/src/colonizer1.cpp.i
.PHONY : src/colonizer1.cpp.i

src/colonizer1.s: src/colonizer1.cpp.s

.PHONY : src/colonizer1.s

# target to generate assembly for a file
src/colonizer1.cpp.s:
	$(MAKE) -f CMakeFiles/col1.dir/build.make CMakeFiles/col1.dir/src/colonizer1.cpp.s
.PHONY : src/colonizer1.cpp.s

src/fortress.o: src/fortress.cpp.o

.PHONY : src/fortress.o

# target to build an object file
src/fortress.cpp.o:
	$(MAKE) -f CMakeFiles/fort.dir/build.make CMakeFiles/fort.dir/src/fortress.cpp.o
.PHONY : src/fortress.cpp.o

src/fortress.i: src/fortress.cpp.i

.PHONY : src/fortress.i

# target to preprocess a source file
src/fortress.cpp.i:
	$(MAKE) -f CMakeFiles/fort.dir/build.make CMakeFiles/fort.dir/src/fortress.cpp.i
.PHONY : src/fortress.cpp.i

src/fortress.s: src/fortress.cpp.s

.PHONY : src/fortress.s

# target to generate assembly for a file
src/fortress.cpp.s:
	$(MAKE) -f CMakeFiles/fort.dir/build.make CMakeFiles/fort.dir/src/fortress.cpp.s
.PHONY : src/fortress.cpp.s

src/histogram.o: src/histogram.cpp.o

.PHONY : src/histogram.o

# target to build an object file
src/histogram.cpp.o:
	$(MAKE) -f CMakeFiles/histogram.dir/build.make CMakeFiles/histogram.dir/src/histogram.cpp.o
.PHONY : src/histogram.cpp.o

src/histogram.i: src/histogram.cpp.i

.PHONY : src/histogram.i

# target to preprocess a source file
src/histogram.cpp.i:
	$(MAKE) -f CMakeFiles/histogram.dir/build.make CMakeFiles/histogram.dir/src/histogram.cpp.i
.PHONY : src/histogram.cpp.i

src/histogram.s: src/histogram.cpp.s

.PHONY : src/histogram.s

# target to generate assembly for a file
src/histogram.cpp.s:
	$(MAKE) -f CMakeFiles/histogram.dir/build.make CMakeFiles/histogram.dir/src/histogram.cpp.s
.PHONY : src/histogram.cpp.s

src/segmentation.o: src/segmentation.cpp.o

.PHONY : src/segmentation.o

# target to build an object file
src/segmentation.cpp.o:
	$(MAKE) -f CMakeFiles/segm.dir/build.make CMakeFiles/segm.dir/src/segmentation.cpp.o
.PHONY : src/segmentation.cpp.o

src/segmentation.i: src/segmentation.cpp.i

.PHONY : src/segmentation.i

# target to preprocess a source file
src/segmentation.cpp.i:
	$(MAKE) -f CMakeFiles/segm.dir/build.make CMakeFiles/segm.dir/src/segmentation.cpp.i
.PHONY : src/segmentation.cpp.i

src/segmentation.s: src/segmentation.cpp.s

.PHONY : src/segmentation.s

# target to generate assembly for a file
src/segmentation.cpp.s:
	$(MAKE) -f CMakeFiles/segm.dir/build.make CMakeFiles/segm.dir/src/segmentation.cpp.s
.PHONY : src/segmentation.cpp.s

src/thermal_contour.o: src/thermal_contour.cpp.o

.PHONY : src/thermal_contour.o

# target to build an object file
src/thermal_contour.cpp.o:
	$(MAKE) -f CMakeFiles/t_contour.dir/build.make CMakeFiles/t_contour.dir/src/thermal_contour.cpp.o
.PHONY : src/thermal_contour.cpp.o

src/thermal_contour.i: src/thermal_contour.cpp.i

.PHONY : src/thermal_contour.i

# target to preprocess a source file
src/thermal_contour.cpp.i:
	$(MAKE) -f CMakeFiles/t_contour.dir/build.make CMakeFiles/t_contour.dir/src/thermal_contour.cpp.i
.PHONY : src/thermal_contour.cpp.i

src/thermal_contour.s: src/thermal_contour.cpp.s

.PHONY : src/thermal_contour.s

# target to generate assembly for a file
src/thermal_contour.cpp.s:
	$(MAKE) -f CMakeFiles/t_contour.dir/build.make CMakeFiles/t_contour.dir/src/thermal_contour.cpp.s
.PHONY : src/thermal_contour.cpp.s

src/thermal_image.o: src/thermal_image.cpp.o

.PHONY : src/thermal_image.o

# target to build an object file
src/thermal_image.cpp.o:
	$(MAKE) -f CMakeFiles/t_image.dir/build.make CMakeFiles/t_image.dir/src/thermal_image.cpp.o
.PHONY : src/thermal_image.cpp.o

src/thermal_image.i: src/thermal_image.cpp.i

.PHONY : src/thermal_image.i

# target to preprocess a source file
src/thermal_image.cpp.i:
	$(MAKE) -f CMakeFiles/t_image.dir/build.make CMakeFiles/t_image.dir/src/thermal_image.cpp.i
.PHONY : src/thermal_image.cpp.i

src/thermal_image.s: src/thermal_image.cpp.s

.PHONY : src/thermal_image.s

# target to generate assembly for a file
src/thermal_image.cpp.s:
	$(MAKE) -f CMakeFiles/t_image.dir/build.make CMakeFiles/t_image.dir/src/thermal_image.cpp.s
.PHONY : src/thermal_image.cpp.s

src/thermal_speed.o: src/thermal_speed.cpp.o

.PHONY : src/thermal_speed.o

# target to build an object file
src/thermal_speed.cpp.o:
	$(MAKE) -f CMakeFiles/t_speed.dir/build.make CMakeFiles/t_speed.dir/src/thermal_speed.cpp.o
.PHONY : src/thermal_speed.cpp.o

src/thermal_speed.i: src/thermal_speed.cpp.i

.PHONY : src/thermal_speed.i

# target to preprocess a source file
src/thermal_speed.cpp.i:
	$(MAKE) -f CMakeFiles/t_speed.dir/build.make CMakeFiles/t_speed.dir/src/thermal_speed.cpp.i
.PHONY : src/thermal_speed.cpp.i

src/thermal_speed.s: src/thermal_speed.cpp.s

.PHONY : src/thermal_speed.s

# target to generate assembly for a file
src/thermal_speed.cpp.s:
	$(MAKE) -f CMakeFiles/t_speed.dir/build.make CMakeFiles/t_speed.dir/src/thermal_speed.cpp.s
.PHONY : src/thermal_speed.cpp.s

src/threshold.o: src/threshold.cpp.o

.PHONY : src/threshold.o

# target to build an object file
src/threshold.cpp.o:
	$(MAKE) -f CMakeFiles/thresh.dir/build.make CMakeFiles/thresh.dir/src/threshold.cpp.o
.PHONY : src/threshold.cpp.o

src/threshold.i: src/threshold.cpp.i

.PHONY : src/threshold.i

# target to preprocess a source file
src/threshold.cpp.i:
	$(MAKE) -f CMakeFiles/thresh.dir/build.make CMakeFiles/thresh.dir/src/threshold.cpp.i
.PHONY : src/threshold.cpp.i

src/threshold.s: src/threshold.cpp.s

.PHONY : src/threshold.s

# target to generate assembly for a file
src/threshold.cpp.s:
	$(MAKE) -f CMakeFiles/thresh.dir/build.make CMakeFiles/thresh.dir/src/threshold.cpp.s
.PHONY : src/threshold.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... cfarAlgo"
	@echo "... rebuild_cache"
	@echo "... histogram"
	@echo "... t_image"
	@echo "... fort"
	@echo "... cfar"
	@echo "... kalman_cfar"
	@echo "... foil"
	@echo "... t_contour"
	@echo "... KFtrack"
	@echo "... t_speed"
	@echo "... blur"
	@echo "... col1"
	@echo "... thresh"
	@echo "... ycrcb"
	@echo "... segm"
	@echo "... edit_cache"
	@echo "... src/CFARnKF.o"
	@echo "... src/CFARnKF.i"
	@echo "... src/CFARnKF.s"
	@echo "... src/KFtrack.o"
	@echo "... src/KFtrack.i"
	@echo "... src/KFtrack.s"
	@echo "... src/Smoothing.o"
	@echo "... src/Smoothing.i"
	@echo "... src/Smoothing.s"
	@echo "... src/Ycrcb.o"
	@echo "... src/Ycrcb.i"
	@echo "... src/Ycrcb.s"
	@echo "... src/airfoil.o"
	@echo "... src/airfoil.i"
	@echo "... src/airfoil.s"
	@echo "... src/cfar.o"
	@echo "... src/cfar.i"
	@echo "... src/cfar.s"
	@echo "... src/cfarAlgo.o"
	@echo "... src/cfarAlgo.i"
	@echo "... src/cfarAlgo.s"
	@echo "... src/colonizer1.o"
	@echo "... src/colonizer1.i"
	@echo "... src/colonizer1.s"
	@echo "... src/fortress.o"
	@echo "... src/fortress.i"
	@echo "... src/fortress.s"
	@echo "... src/histogram.o"
	@echo "... src/histogram.i"
	@echo "... src/histogram.s"
	@echo "... src/segmentation.o"
	@echo "... src/segmentation.i"
	@echo "... src/segmentation.s"
	@echo "... src/thermal_contour.o"
	@echo "... src/thermal_contour.i"
	@echo "... src/thermal_contour.s"
	@echo "... src/thermal_image.o"
	@echo "... src/thermal_image.i"
	@echo "... src/thermal_image.s"
	@echo "... src/thermal_speed.o"
	@echo "... src/thermal_speed.i"
	@echo "... src/thermal_speed.s"
	@echo "... src/threshold.o"
	@echo "... src/threshold.i"
	@echo "... src/threshold.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

